var canvas = document.getElementById("game");
var context = canvas.getContext("2d");
context.font = "20px Arial";
context.fillStyle = "white";
context.textAlign = "center";
context.fillText("This text was generated by game.js", 200, 30);